### ISSUE TITLE
IFC Export config for Site

### ISSUE THREAD

**Issue by torgeirfadnes** [Autodesk/revit-ifc#17]
It would be good to have an option to add a fixed Site to the export config. This way, we are no longed dependant on the correct site being set when doing multiple exports. This is an issue on projects where we operate with multiple sites, and some users change sites from what is correct for the IFC export.

**Comment by WawanSolihin** [comment]
I believe it is more a matter of standardization for models to have a uniform shared coordinates. IFC4 has improvements in term of georeference so that the coordinate system can be made more consistent. Export configuration can be set using Project based point (or Survey point). See descriptions in Wiki: https://github.com/Autodesk/revit-ifc/wiki/Mapping-geo-reference-in-IFC4

**Comment by torgeirfadnes** [comment]
Hi. It seems that we have a misunderstanding. The issue is that we might have several sites in Revit, but only "current site" will be used when exporting. This means that if another user just changed the site, you would get different coordinates for your export. 

So to solve this I would like it to be possible to specify which site you would want to use for export.

I don't think this is anything IFC4 or IFC5 would fix for that matter. It is about specifying which coordinates (or sites) you want to use for the specific setup.

To me it could be solved easily with three options:
Project Base Point
Survey Point (Current)
Survey Point (Specify) [dropdown list of all available sites]

How about it?

**Comment by WawanSolihin** [comment]
I still think this is a standardization issue. For IFC export to produce consistent placement (in the case of multiple export, they must align), they have to be consistent in Revit (e.g. if you link them) and this can only be ensured when the coordinate base somehow is consistent. In most cases, it will use shared coordinates. I mentioned the use of georeference because it is what generally need to be specified for a project (that is located on ground). For related sites, I believe they will share the same Survey Point (often called Survey control point), while the project base points can be offset differently each located the most convenient for that building. Allowing export to select a site that may not align will also cause issue when putting the IFC files together. I believe users must be responsible in ensuring the models are aligned first before exporting, rather than making exporter to change the alignment.

**Comment by torgeirfadnes** [comment]
I guess we disagree on this subject, or may even still not understand each other. 
My point is that we may, in the same project, operate with different coordinate systems. In Norway we have NTM and UTM, as well as a localized coordinate system, though wider than the base point it self.

So some users needs to use the world coordinate system and others want to use a local coordinate system. That is because eg. the municipal and outdoor contractor require global coordinates, but the client and indoors contractor typically want local coordinates (with true north). So both are using shared coordinates, but they swap between sites when needed.

However this is not a user setting, so when anyone changes the site, they change it for everyone upon sync. 

This means that if I have an automated process to export IFC files to the interior building contractor, and another setup to produce IFC's with the global coordinates, I have to manually change the sites to ensure that the base points is correct respectively.

In my opinion it would be much better to be able to specify which site I want for this export setup, and I don't have to worry if anyone has changed to another site in the mean time.

This has been discussed with @AngelVelezSosa on several occasions and I do think it has been clear that this is needed to ensure a safe and efficient workflow on IFC export. Especially when it comes to automated exports.

**Comment by AngelVelezSosa** [comment]
I will set up a meeting with @WawanSolihin and @torgeirfadnes  to discuss next steps.

**Comment by tsolsen** [comment]
I have run into the same problems as @torgeirfadnes, especially when working in Norway, but also when doing projects locally.
Both towards IFC and internally in RVT, it's a problem, that we can't: export to a specified site other than current, and can't annotate to different sites at the same time.
