### ISSUE TITLE
 IFC Exporter 2020.2 does not work

### ISSUE THREAD

**Issue by HenkMolhoek** [Autodesk/revit-ifc#214]
![Export issue](https://user-images.githubusercontent.com/45469583/87549989-d0eca400-c6ae-11ea-89c2-539c282407cc.PNG)

IFC Exporter 2020.2 does not work. 
I try to export 2 walls and get the following message.

**Comment by WawanSolihin** [comment]
Hmm, can you send me the revit file?

**Comment by HenkMolhoek** [comment]
The problem occurs if the 2020.1 is uninstalled and then 2020.2 is installed.
if 2020.1 is not uninstalled it will work. But is that the right method?

**Comment by WawanSolihin** [comment]
Hmm I tested this and it is OK. Let me try to do the same again. By right you do not need to uninstall 2020.1, the installer will update it to 2020.2

**Comment by HenkMolhoek** [comment]
we tried on 2 machines with uninstall.
and 1 without uninstall.
Without uninstall there are 2 versions under software.


With uninstall
![software with uninstall 2020 1](https://user-images.githubusercontent.com/45469583/87554150-11025580-c6b4-11ea-887a-31ee285ac482.PNG)

without uninstall
![software without uninstall 2020 1](https://user-images.githubusercontent.com/45469583/87554184-1b245400-c6b4-11ea-98df-be37498011a6.png)

**Comment by WawanSolihin** [comment]
There seems to be a problem with some product code that causes the older version (20.1.0.1) is not removed when installing 20.2.0. For now, I would suggest to do the following:
1. Uninstall the existing 20.1.0.1 first from the Control Panel
2. Install the 20.2.0.0

I will be creating the new installer that will use the correct code. This will remove existing 20.1.0.1 upon installation. However, for now I would recommend everyone to uninstall the existing version manually because it will work only if the existing version is 20.1.0.1. If it is the older version, it may still have problem.

**Comment by WawanSolihin** [comment]
Installer has been updated. It should work now

**Comment by HenkMolhoek** [comment]
Wij gebruiken Revit 2020.1 werkt de exporter 2020.2 met revit 2020.1? Of werkt deze alleen voor Revit 2020.2?

**Comment by WawanSolihin** [comment]
It should work for all 2020.x versions. IFCExporter uses Revit APIs and generally minor version change will not affect APIs.

**Comment by HenkMolhoek** [comment]
We have installed and uninstalled the exporter several times but I keep getting the same error. With Revit 2020.1.
We tried this on multiple computers.

**Comment by WawanSolihin** [comment]
I recommend to uninstall the existing 2020.1 and download the updated 2020.2 installer (the first version has this problem). But I think the guid has been corrected so the updated installer should be able to replace 2020.1 with 2020.2. 
Download from the same link: https://github.com/Autodesk/revit-ifc/releases/download/IFC_v20.2.0.0/IFC.for.Revit.2020.version.20.2.0.0.msi. This has been updated

**Comment by HenkMolhoek** [comment]
we tried that but the ifc exporter 2020.2 keeps giving the same message.

**Comment by WawanSolihin** [comment]
Actually the reason for that message is simply it tries to load the default (the version out of the box) and it then tries to load the the open source DLLs. It fails because they mismatch. You can see in the export window if the title does not have version number, it loads the original out of the box version of UI. In this case due to mismatch you will get the above issue.
![image](https://user-images.githubusercontent.com/31854582/88404218-2daf3380-ce00-11ea-9597-bd4605bfde8e.png)
 
When you used the first version of the installer, you will get Revit 20.1 and 20.2 showing up in the Control Panel. In this case it is best to uninstall both (start clean), and probably best to make sure that the folder is also clean (C:\ProgramData\Autodesk\ApplicationPlugins\IFC 2020.bundle\Contents\2020).

I tested it with various combinations on my machine and it works as expected, i.e. it replaces the 20.1.

**Comment by HenkMolhoek** [comment]
Same problem Het IFC Exporter is 20.2.0.0 the revit version 2020.1
![Revit](https://user-images.githubusercontent.com/45469583/88456876-d5207a80-ce81-11ea-9fca-12f5fe396c14.png)

![2020-07-25_14-16-53](https://user-images.githubusercontent.com/45469583/88456856-a6a29f80-ce81-11ea-8099-7679dd2bc871.png)
![Export issue](https://user-images.githubusercontent.com/45469583/88456860-aacebd00-ce81-11ea-87da-17289373599d.PNG)

**Comment by WawanSolihin** [comment]
Ah, maybe because you are still using 2020.1. I compiled the addin using 2020.2.
Is there any reason you cannot update the Revit 2020 installation to 2020.2?
Otherwise, I think we may need to compile it for 2020.1. This is a little bit complicated since I have to uninstall my 2020 and reinstall it from 2020.0 and update it to 2020.1.
If you can update Revit to 2020.2, it will probably solve your problem.

**Comment by HenkMolhoek** [comment]
Our company policy is that we only use releases and not a hotfix. We are using 2020.1 because there are issues in 2020.2 that has been resolved with a hotfix. We are waiting for an official update 2020.3 before updating.

**Comment by AngelVelezSosa** [comment]
I don't think the version of 2020.X should matter for the exporter; we will keep trying to figure out why it doesn't work for you.  On a related topic, note that there is no guarantee that there will be a 2020.3.  I don't know if you use the word "hotfix" differently, but 2020.2.X versions are considered official releases; they just have no new features, just stability and performance enhancements.

**Comment by AngelVelezSosa** [comment]
Update: we have verified that indeed it _doesn't_ work with 2020.1, although it does with 2020.2.  We are looking to see if we really on API from 2020.2, or a similar issue.  In the meantime, either update to Revit 2020.2.X, or uninstall the latest version.  We will try to patch the open source so it works with all versions of 2020.

**Comment by AngelVelezSosa** [comment]
Problem found.  The open source currently relies on an API that was added to Revit 2020.2, but not previous versions.  We will use a previous version of the API that is available in 2020 and 2020.1, and update the open source so that you can use it.  Thanks for pointing this out to us!

**Comment by WawanSolihin** [comment]
We have updated the installer with the issue preventing the exporter to work properly in 2020.1. Please get it from: https://github.com/Autodesk/revit-ifc/releases/download/IFC_v20.2.1.0/IFC.for.Revit.2020.version.20.2.1.0.msi
Thanks.

**Comment by HenkMolhoek** [comment]
Thanks for solving the problem. We have tested the ifc exporter and it works.
