### ISSUE TITLE
Which version of VS can run this code rightly?

### ISSUE THREAD

**Issue by awefire** [Autodesk/revit-ifc#22]
I use VS 2015 run it,but get some error.So, which version of VS can run this code rightly?
thanks in advance.

**Comment by Febfire** [comment]
I install project completely.
But i don't know how to debug the source code.How to debug the Revit.IFC.Expoert ?

**Comment by WawanSolihin** [comment]
You need to attach your debugger to Revit.exe. You need to do following steps:
1. Open the solution in your Visual Studio
2. Start your Revit as usual (make sure you have copied the compiled dlls from your VS to the location you have installed the plugins earlier)
3. From VS menu: Debug, select "Attach to Process..."
4. Find Revit.exe process and select it to debug
5. Perform IFC export. You would need to put a breakpoint in the appropriate code in the Revit.IFC.Export to enable you to break the execution and to step through the debugger

**Comment by Febfire** [comment]
hi wawansolihin,I understand.
But i don't know where is the entrance of ifcexport,i should put a breakpoint where at the begining?
thanks.

**Comment by jmirtsch** [comment]
Typically the installer deploys the plugin dlls to the equivalent of C:\Program Files (x86)\Revit IFC 2019\

There was a post build command to do this but it was removed (and should be restored shorly).  Because of all of the other files etc, it's best to have run the plugin installer prior to compiling and debugging so everything is in place (standard deployment uses a different location and dll).  

To catch the start of export, put a break point in the method  public void ExportIFC(Autodesk.Revit.DB.Document document, ExporterIFC exporterIFC, Autodesk.Revit.DB.View filterView) in the file https://github.com/Autodesk/revit-ifc/blob/master/Source/Revit.IFC.Export/Exporter/Exporter.cs

It's also possible to nominate Autodesk as the application to run as per this image.  I'm seeing if we can include this into the git repository files (at moment .csproj.user files are excluded from git commits).

**Comment by Febfire** [comment]
thank you,jmirtsch.
I use VS2015 open the Revit IFC 2018 solution.But i got a Migration report about revit-ifc-Revit2018\Install\RevitIFCSetupWix\RevitIFCSetupWix.wixproj.I try to open it at VS2017 and VS2013,all failed.What should i do? @jmirtsch

**Comment by jmirtsch** [comment]
Do you have the wix addin for Visual Studio installed?
https://marketplace.visualstudio.com/items?itemName=RobMensching.WiXToolset

Even if this project fails to load, you should be able to build and debug the revit plugins.
I'll test this next chance I get on my computer with an older version of visual studio.

**Comment by Febfire** [comment]
thank you very much.
And i have a question about your project GeometryGymIFCExamples.Can you give me a tip?

**Comment by Febfire** [comment]
Now,i have two problems:
1, I use IFC Exporter for Revit 2014,after i install the .msi ,i can't find Installation directory.
     Because i did not find the step to set install direction in the setup wizard.
2, I use Export IFC 2018,i got some errors in Revit.IFC.Export such as "can not find namespace Autodesk" 
     and so on.I'm sure my referecce is correct.

**Comment by jmirtsch** [comment]
You'll see there are branches set up to support Revit 2018 and Revit 2017.  
It's a task to add branches and "downgrade" to Revit 2014.  It would be advised to step version by version, ie 2016, then 2015 and then 2014.  You'll need to downgrade the dotnet versions etc.  This would take some time and it's not something I personally can prioritize.  Did you use the branch for 2018?

The source forge repository had a different approach and saved different folders for the different versions of revit.  If you want to more readily build for 2014 (noting it will ignore all the subsequent fixes and improvements) then I'd pull the code from there.

**Comment by Febfire** [comment]
yeah,i want to build for 2014.
thank you.

**Comment by AngelVelezSosa** [comment]
Are you looking for the code for the 2014 version?  You can get that from the old SourceForge project, but you will have to do some work to get it to compile.  https://sourceforge.net/projects/ifcexporter/

**Comment by Febfire** [comment]
yeah,i have got the code for 2014 on sourceforge.
But my problem is how to get it to compile.I according to the "Building the Revit IFC Export Open Source Code.pdf",and i have compiled successfully.I install "IFC Revit for 2014.msi",then attach to the process of Revit(2014).exe.However,it did not hit the breakpoint that i put at function "RevitIFC(Autodesk.Revit.DB.Document document, ExporterIFC exporterIFC, Autodesk.Revit.DB.View filterView)".
And i can't find where the plugin"IFC Revit for 2014"installed,because the install wizard doesn't have step to set direction.
So,can you give me a detailed steps to debug the source that export rvt to ifc.
thanks,i'm grateful to you. @WawanSolihin @jmirtsch @AngelVelezSosa
