### ISSUE TITLE
IfcProjectedCRS

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#234]
We are trying to get an IFC file to validate trough this MVD: http://test-bimvalbygg.dibk.no/. When IFC4 is selected as schema, we get an IfcProjectedCRS entety, but

**How can we set IfcProjectedCRS.Name?**

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcrepresentationresource/lexical/ifcprojectedcrs.htm

**Comment by AngelVelezSosa** [comment]
We are actively working on UI for this at the moment.  We hope to have this in an open source update.  @WawanSolihin, FYI.

**Comment by WawanSolihin** [comment]
Currently the attributes to IFCProjectedCRS can be set using parameters attached to Project Info. You may find them in the supplied shared parameter file:
PARAM	9ed03820-7425-4d90-868e-2ab0f5319495	ProjectGlobalPositioning.CRSName	TEXT		2	1		1
PARAM	e4090d66-012c-45fe-9ac9-4cfe51c0dd29	ProjectGlobalPositioning.CRSDescription	TEXT		2	1		1
PARAM	e66c0e06-0383-480f-854e-950bb0d435f8	ProjectGlobalPositioning.CRSGeodeticDatum	TEXT		2	1		1
PARAM	bc47059f-e418-41f2-85b9-8b556dacae5e	ProjectGlobalPositioning.CRSVerticalDatum	TEXT		2	1		1
PARAM	b1d60aea-e267-4ca1-b899-cb06d5eaa9c8	ProjectGlobalPositioning.CRSMapProjection	TEXT		2	1		1
PARAM	91150f20-dc6c-4691-be1e-fe0ed0dfae6f	ProjectGlobalPositioning.CRSMapZone	TEXT		2	1		1
PARAM	093a80c9-4a77-4076-a71c-041e3521608c	ProjectGlobalPositioning.CRSMapUnit	TEXT		2	1		1

For the IfcMapConversion that points to the IfcProjectedCRS though what in the Open Source currently is not the latest/improved version yet.

In the current Open Source version, it will take a Survey Point to set the Eastings, Northings and the OthogonalHeight, while the XAxisAbscissa and XAxisOrdinate will be set based on the True North value. In this version, the values of Eastings, Northings and OrthogonalHeight can be overriden by parameters to the Project Info: ProjectGlobalPositioning.Eastings, ProjectGlobalPositioning.Northings, ProjectGlobalPositioning.OrthogonalHeight. But I would advise NOT to use these as they will be removed when we apply the next updates to the open source code. The improved version will set the Eastings, Northings, and OrthogonalHeight from the selected Coordinate Reference (selected upon export), and the IfcProjectedCRS.Name will be set from the value Revit may import from the Topography coming from AutoCAD/Civil3D, however it still can be overridden by ProjectGlobalPositioning.CRSName since IFC only accepts EPSG codes.

**Comment by Moult** [comment]
The geolocation MicroMVD provides a list of requirements for geolocation, as well as a guide on how to achieve this in Revit: https://wiki.osarch.org/index.php?title=Geolocation_MicroMVD

The guide itself: https://wiki.osarch.org/index.php?title=Revit_geolocation

**Comment by eibre** [comment]
@WawanSolihin How do you format the input in last line `PARAM 093a80c9-4a77-4076-a71c-041e3521608c ProjectGlobalPositioning.CRSMapUnit TEXT 2 1 1` to get the unit correct in IFC export?
![image](https://user-images.githubusercontent.com/5968613/98107706-2dacde00-1e9b-11eb-8b10-106269b999cd.png)

**Comment by eibre** [comment]
![image](https://user-images.githubusercontent.com/5968613/98107773-4917e900-1e9b-11eb-96a6-b7a59d9584ee.png)

**Comment by eibre** [comment]
Not yet supportet? 
https://github.com/Autodesk/revit-ifc/blob/7b0bde429b94fd5399fb8121fa0278339968edf0/Source/Revit.IFC.Export/Exporter/Exporter.cs#L2673

**Comment by WawanSolihin** [comment]
Does not seem to be properly supported. Will add this as an action item targeted for the next release (an IFC4 RV Arch and Struc export certified version) that is coming soon.

**Comment by Moult** [comment]
@eibre can you help update the wiki about this shortcoming? https://wiki.osarch.org/index.php?title=Revit_geolocation

**Comment by eibre** [comment]
@Moult Sure! The guide on the wiki was exactly what we needed in this case, nice job.
