### ISSUE TITLE
New ifc exporter for Revit 2018

### ISSUE THREAD

**Issue by Nattikus** [Autodesk/revit-ifc#269]
Hi, 
more a question than an issue: Will Revit 2018 be supported with IFC exporter that contains the new certified IFC4 MVD and if yes, then when do you plan to do publish it?

Thanx

**Comment by AngelVelezSosa** [comment]
Short answer: no plans to do that.
Long answer: We always need to balance time on new functionality/bug fixes vs. time to back-submit changes.  Back-submitting can be a time-consuming process because of API changes between releases and other similar issues.  Normally, we support the current shipping version and the previous version for active updates as a compromise to that.  In this particular case, we have already submitted to Revit 2020 and 2021 branches, and do plan to do Revit 2019 since it is a big improvement.

**Comment by Nattikus** [comment]
thanx for your prompt reply. have a nice day
