### ISSUE TITLE
large revit project export IFC  error with "There has been an unrecoverable error during export. Export will now be aborted" in Revit 2017 with version 19.1.0.0 export code in Revit2017 Branch.

### ISSUE THREAD

**Issue by blueskytiger** [Autodesk/revit-ifc#27]
How to export large revit project?

**Comment by FranciscoCTI** [comment]
I have the same problem exporting in 2019

**Comment by WawanSolihin** [comment]
How big is the model? We have a known limitation due to the IFC toolkit we use in term of the total number of IFC entities for very large model. We are currently working on the replacement of the toolkit. 
It will be very helpful if we could have access to the model to see whether the new toolkit solves the issue before we release it in the very near future.
