### ISSUE TITLE
Steel elements not exporting anymore

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#282]
With IFC export v 21.2.0.0 most of the steel elements are no exportet. And also concrete elements which are connected to steel are gone! 
![image](https://user-images.githubusercontent.com/5968613/110034171-720d9500-7d3a-11eb-892a-e318e949c295.png)

Some beams and a wall is floating away;
![image](https://user-images.githubusercontent.com/5968613/110034246-7e91ed80-7d3a-11eb-9d4b-3bf6af4b269d.png)

I have checked "export steel elements" and some of them are exported:
(but here the steel beam is not cut correctly)
![image](https://user-images.githubusercontent.com/5968613/110034379-aa14d800-7d3a-11eb-84b1-3a123b1d36cb.png)

Please fix this! Our deliveries are IFC and we can't use any of Revits features that is not supported by the IFC-exporter. 

[missing steel.ifc.txt](https://github.com/Autodesk/revit-ifc/files/6086770/missing.steel.ifc.txt)

**Comment by BIMLUND** [comment]
We have the same issue. Steel connections dosent export anymore...

**Comment by AngelVelezSosa** [comment]
For now please uninstall the open source version if you need steel connections support.  We are actively looking into this issue with the AdvanceSteel team to see how to proceed.

**Comment by BIMLUND** [comment]
> For now please uninstall the open source version if you need steel connections support. We are actively looking into this issue with the AdvanceSteel team to see how to proceed.
![Error](https://user-images.githubusercontent.com/81314195/112641889-14550000-8e43-11eb-9445-975c56a2806a.png)

Thanks! But hten we have the error where we only can export in Internal Orgin. If we choose Project Base Point some element is still stuck in Internal... So right now we need to go back to Tekla. We'll try Revit for Steel in the future thanks.

**Comment by Revitlooser** [comment]
Also if exporting IFC from advanced steel instead of Revit the IFC file have the same issue in Solibri, but in BIMCollab Zoom it looks correct. 
![image](https://user-images.githubusercontent.com/35491203/115558574-2c3d6980-a2b3-11eb-87ac-d6e250c62ebb.png)

**Comment by AngelVelezSosa** [comment]
To the original issue - we have identified the issue and are working through the process of getting the fix to open source.

**Comment by A-drt** [comment]
Hi, tried to export a revit model with steelConnections and no problem by my side.
Info:
Revit 2022
IfcExporter: 22.1.0.0

import on trimble connect 11.1.4.307

**Comment by eibre** [comment]
I have the same issue as before in v. 21.2.1.0. Wasn't this fixed @WawanSolihin ?

**Comment by WawanSolihin** [comment]
This a problem with the way Steel Connection code is structured. It works in the official Revit installer, but won't work well with the Open Source releases. I actually have a fix already for this (both 2021 and 2022), but I cannot release that update yet due to pending approval for releasing additional DLL for the Steel Connection together with the Open Source. We hope we will get that approval soon.

**Comment by A-drt** [comment]
hi @WawanSolihin does this issue was corrected in 2022.2.0.0 ? there is no mention about steel connection issue.

**Comment by WawanSolihin** [comment]
Unfortunately not yet. It is not so much of technical issue, but some admin issue that is still preventing us in deploying the  fix. Hopefully we can get it resolved soon.

**Comment by c-falardeau** [comment]
Is version 21.4.0.0 fixes this issue?

**Comment by WawanSolihin** [comment]
Yes, it should work now

**Comment by c-falardeau** [comment]
Ok because I tried the solution. I found the assembly is loaded when ExportASElements is invoked, it seems to throw a System.NullReferenceException exception.

**Comment by WawanSolihin** [comment]
Do you have a sample model for us to test?

**Comment by c-falardeau** [comment]
I found the problem!.
Autodesk.SteelConnections.ASIFC.dll reference itself the Revit.IFC.Export.dll and need to access the ExporterCacheManager class while processing the the steel elements.

In BIM Track we forked the Revit.IFC.Export and Revit.IFC.Common project and we build our own version of them.
We rename these assemblies to BIMOne.Revit.IFC.Export and BIMOne.Revit.IFC.Common and package them into our addin to implement a customize version of the exporter. We have renamed our assemblies to prevent name clashing and allow .NET load our own assemblies for our addin context. We also did that do avoid overriding the IFC exporter delivered with Revit.

When exporting, the ExportIFC method is called and prepares the export options cache. 
The exporter loads dynamically the Autodesk.SteelConnections.ASIFC.dll and calls the ExportASElements method. Since the assembly references the original Revit.IFC.Export.dll, an exception is thrown because the static method ExportASElements try to access a different version of the ExporterCacheManager class (the Revit one).

 Revit.IFC.Export.dll and Autodesk.SteelConnections.ASIFC.dll a circular dependencies at runtime by the way.

Best regards,
Christian

**Comment by c-falardeau** [comment]
I found the problem!.
Autodesk.SteelConnections.ASIFC.dll reference itself the Revit.IFC.Export.dll and need to access the ExporterCacheManager class while processing the the steel elements.

In our product we forked the Revit.IFC.Export and Revit.IFC.Common project and we build our own version of them.
We rename these assemblies to MyCompany.Revit.IFC.Export and MyCompany.Revit.IFC.Common and package them into our addin to implement a customize version of the exporter. We have renamed our assemblies to prevent name clashing and allow .NET load our own assemblies for our addin context. We also did that do avoid overriding the IFC exporter delivered with Revit.

When exporting, the ExportIFC method is called and prepares the export options cache.
The exporter loads dynamically the Autodesk.SteelConnections.ASIFC.dll and calls the ExportASElements method. Since the assembly references the original Revit.IFC.Export.dll, an exception is thrown because the static method ExportASElements try to access a different version of the ExporterCacheManager class (the Revit one).

Revit.IFC.Export.dll and Autodesk.SteelConnections.ASIFC.dll a circular dependencies at runtime by the way.

Best regards,
Christian

**Comment by WawanSolihin** [comment]
Thanks Christian, you identify the issue correctly. ASIFC.dll makes a reference to Revit.IFC.Export.dll. This actually causes it not to work with the open source before (because it was compiled to refer to the standard one that comes with the Revit installer). This version (21.4.0.0) includes recompiled ASIFC.dll with the the open source dll. This solves the issue if you do not have your own version of the DLL, which in this case you have that exactly. This is currently a known issue and we are still trying to overcome it by making ASIFC as part of the open source. But this will take time because we need to navigate all the standard process involving our legal team, etc.

**Comment by c-falardeau** [comment]
Thanks for you answer and hope to see any follow up on this issue soon :)

**Comment by AngelVelezSosa** [comment]
The latest version is _supposed_ to fix that issue.  More specifically - the install associated with the solution should have the version of ASIFC.dll that you need.  If you are building your own solution, that should fix the issue.  If you just get the install for 21.4.0, it should just work. 
The remaining issue is that _custom_ exporters that need steel connections exported won't work until we can open source ASIFC.dll.  I don't know when that will happen.  But for everyday use of the supplied installs, it should be fine.

**Comment by c-falardeau** [comment]
> The remaining issue is that custom exporters that need steel connections exported won't work until we can open source ASIFC.dll. I don't know when that will happen. But for everyday use of the supplied installs, it should be fine.
This is our case

**Comment by AngelVelezSosa** [comment]
Right - that's unfortunately less fixable for now for the reasons you stated above.  One possibility - it is possible to _extend_ the exporter by building an exporter on top of it, instead of actually modifying the existing exporter.  Is that possible in your case?

**Comment by tsemeo** [comment]
Fixed in
[Release 22.2.1.0 for Revit 2022](https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v22.2.1.0)
[Release 21.4.0.0 for Revit 2021](https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v21.4.0.0)

**Comment by HNicol111** [comment]
Is there a fix for this in Revit 2020?

**Comment by AngelVelezSosa** [comment]
Current the fix is only for Revit 2021 and Revit 2022.

**Comment by c-falardeau** [comment]
> Right - that's unfortunately less fixable for now for the reasons you stated above. One possibility - it is possible to _extend_ the exporter by building an exporter on top of it, instead of actually modifying the existing exporter. Is that possible in your case?

Unfortunately in our case, it is not possible.

Is there a issue opened to solve the matter about making open source the  ASIFC.dll dll ?

**Comment by AngelVelezSosa** [comment]
Yes, that's something we want to happen.  I don't have a timeframe for it.

**Comment by c-falardeau** [comment]
> Yes, that's something we want to happen. I don't have a timeframe for it.

Do you have a link to the issue yet?

**Comment by AngelVelezSosa** [comment]
There's an internal issue.  If you want it to be logged here, go ahead and create.
