### ISSUE TITLE
IfcGuids are deleted when primary design option is made secondary

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#314]
@AngelVelezSosa Not sure if this is the right place to post this. Although this is an IFC related issue, there seems to be no relation to the IFC exporter but rather only to Revit core functionality (i.e. reassigning a primary design option).

**Issue:**

IfcGuids of elements in a primary design option are deleted when another option in the design option set is assigned as primary. 

**Why is this bad?**

IfcGuids of elements should not change once they are assigned as changed IfcGuids cause issues in subsequent workflows (e.g. identifying those elements in BCF issues etc.). 

**Expected behaviour:**

IfcGuids of elements in design options are retained regardless of whether the design option is set as primary or not, therefore allowing users to switch primary design options without risk of data loss.

**Steps to reproduce:**
- Create a design option set with two options
- Model a wall in each design option
- Export as IFC (using the setting to write IfcGuids to elements after export)
- Observe how the wall in the primary design option now has an IfcGuid
- Assign the second design option as primary
- Observe how the wall in the formerly primary design option now has an empty IfcGuid parameter - its value was deleted

**Comment by denizmaral** [comment]
Some additions to that topic: 

IfcGUIDs are being deleted because Revit changes the ID of element after switching between options. It means: if you export to IFC, you will get a new GUID for that element because its ID is not same as it has to be. 
Here is a screencast to unterstand the situation:
![IfcGuid_Entwurfsoptionen](https://user-images.githubusercontent.com/55183821/124889209-19475500-dfd7-11eb-9854-b7e47ede979d.gif)

**Comment by AngelVelezSosa** [comment]
Interesting.  So what's your take on this?  We could likely write specific code that when switching between design options, the IfcGUID was preserved if it existed.  I can't quite 100% decide if that is better or worse.  Anyone else have any comments on this?  Or is the issue that the element id changed in the first place?

**Comment by denizmaral** [comment]
Like I said before, that process deletes the element and create a new element with different ID. That behaviour comes from DesignOptions Class.. As workaround we can create an instance parameter and copy the GUID there.

**Comment by AngelVelezSosa** [comment]
Right, but should the DesignOptions Class delete and re-create elements?

**Comment by denizmaral** [comment]
No, it should not because you switch between design options. So the elemens should stay with original ID. In German version when you select the other option as primary option, it is called "create new primary object" so DesignOption class deletes and creates a new object. That is the failure of class.
