### ISSUE TITLE
IFC 2022 on apps.autodesk

### ISSUE THREAD

**Issue by PeterTranberg** [Autodesk/revit-ifc#336]
Is the 2022 version of IFC Exporter going to be accessible from apps.autodesk.com are the new version only available here on github? It is confusing that the two site are unaligned.

**Comment by AngelVelezSosa** [comment]
I'll give you the long answer. :)
Historically, we would always update the open source first, and then update the App store.  We realized a while ago that the open source updates were breaking steel element export, so we decided to continue updating GitHub, but to stall on updating the App store.
In addition, for Revit 2022, we have decided that we want to add the open source updates to the Autodesk Desktop App instead of the App store.  This required some additional work, and there are some issues with the installer that we are trying to resolve.  In addition, we had to resolve the steel elements export issue, although that now has been resolved for Revit 2021 and 2022.
So:
1. We will update the Revit 2021 app store in the near future.
2. We will not plan to add Revit 2022 to the app store, but plan to instead add to the Autodesk Desktop App, assuming that we can resolve the installer issues (I don't see why not, but until they are resolved, they aren't resolved).  If for some reason we can't, then we would go back to the App store.
