### ISSUE TITLE
Roomtag's on een IFC architect model 

### ISSUE THREAD

**Issue by Wouter-MD** [Autodesk/revit-ifc#352]
Can someone help me with making a Tag that can tag the IFCzones/spaces 
with name and space (m2)

**Comment by JOuellette-Autodesk** [comment]
Do you wish to export the Tag in the IFC file as a visible element?

Can you specify the Revit and open source tool versions?

**Comment by Wouter-MD** [comment]
no that not what i mean, 

I want to tag a linked IFC in Revit 
I need the room/space info for making calculations

**Comment by AngelVelezSosa** [comment]
You can't make a room tag because the IFC spaces don't become Revit rooms - they are generic models with the 3D information and parameters.  Converting them into rooms, at least as an option, is on our roadmap.

**Comment by lejla-adsk** [comment]
Check out this LinkedIn Post - a customer just shared an opensource tool which can be used to generative rooms from an IFC file. This creates a Revit model with rooms only, which then can be linked and tagged.
https://www.linkedin.com/feed/update/urn:li:activity:6876158523613433856



From: AngelVelezSosa ***@***.***>
Reply to: Autodesk/revit-ifc ***@***.***>
Date: Monday, 13. December 2021 at 15:28
To: Autodesk/revit-ifc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Autodesk/revit-ifc] Roomtag's on een IFC architect model (#352)


You can't make a room tag because the IFC spaces don't become Revit rooms - they are generic models with the 3D information and parameters. Converting them into rooms, at least as an option, is on our roadmap.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAutodesk%2Frevit-ifc%2Fissues%2F352%23issuecomment-992535956&data=04%7C01%7Clejla.secerbegovic%40autodesk.com%7C2a7e00a1381c43c3ecd008d9be44e32d%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637750025340594451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Bxbm2Flb0t5cNKuc0Yb%2BNMiuFlR3ndX8Iaxthlti1w4%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACGJ2CGBJZA5HJS5RALX4H3UQX7KJANCNFSM5E4XMIKQ&data=04%7C01%7Clejla.secerbegovic%40autodesk.com%7C2a7e00a1381c43c3ecd008d9be44e32d%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637750025340594451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uqSMJWNfeVHfSOrj0LLv6ABpdrU296ba3J%2FMh61xEOI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clejla.secerbegovic%40autodesk.com%7C2a7e00a1381c43c3ecd008d9be44e32d%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637750025340594451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xwGzNzr1sMWjJtSYhipGLUturnbd7lWvXE%2B6DaYC74E%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clejla.secerbegovic%40autodesk.com%7C2a7e00a1381c43c3ecd008d9be44e32d%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637750025340594451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GvSXiQkiJ1ZfjFMUDbhvxEpdCxnfV9TjcMNim6D3WPI%3D&reserved=0>.

**Comment by rolfarchi** [comment]
Hello Leijla,

unfortunately the link to the tool cannot be opened.

Please call again.

Best regards

Rolf

**Comment by lejla-adsk** [comment]
Hi Rolf, I removed the signature which messed up my post - the LinkedIn link left is working on my side and is pointing you directly to the article!
Best, Lejla

**Comment by rolfarchi** [comment]
Hello Lejla,

Unfortunately no change for me (the link has not changed either):
The post cannot be viewed.

Is the contribution from a protected area?

Best regards

Rolf

**Comment by lejla-adsk** [comment]
Hi Rolf, 
I guess you need to be logged in (it's posted in the "Revit Users" group)
Anyway, here the direct links to the resources: 

Youtube Video: https://www.youtube.com/watch?v=4QLh4xoo99A
Github: https://github.com/agnBIM/ifc2room 

Best, Lejla

**Comment by Wouter-MD** [comment]
Hi Lejla, 

Thanks for te Links 
work it with all IFC files it doesn't have to be just from archicad

yesterday i talked to Graphisoft they also have a plugin for revit which has a similar function.
only I know I haven't used their software on another architect's IFC that doesn't use arcicad

Here below stands the link form Graphisoft
https://graphisoft.com/downloads/interoperability
