### ISSUE TITLE
Layer assignments not working in the latest 2021.4.2.0 release

### ISSUE THREAD

**Issue by HL-code** [Autodesk/revit-ifc#353]
We got this issue reported by a customer and could recreate the issue.
Looking in Solibri it seems to export with no layers at all.

**Comment by parrela** [comment]
hello, can you send us a simple model (and the .ifc file) that shows the issue? Thanks.
Andy

**Comment by HL-code** [comment]
Hi Andy

So you where not able to reproduce it using the latest 2021.4.2 exporter ?

It was just an empty file with one wall thats all really.

/HL



tir. 28. sep. 2021, 16:42 skrev parrela ***@***.***>:

**Comment by parrela** [comment]
Oh I see, there is no presentationlayerassignment. I do find that if you add the project parameter IFC CAD Layer to the wall you can assign the layer and it is exported.

**Comment by HL-code** [comment]
Yepp thats the issue.

I know about the Layer parameter.
But i dont think the customer will put in the effort to use it.
Even though its a more flexible method.

**Comment by parrela** [comment]
right, I have filed an issue for it.

**Comment by Moult** [comment]
A consultant recently made me aware of this bug and is asking for advice.

I've just checked all versions since the latest release for Revit 2021 and the bug seems present all the way until v21.2.1.0. So this has been broken since July 2021 I guess. Happy birthday bug!

Currently the only solution I can give is to downgrade, unfortunately. Is there a timeline for this to be solved?

**Comment by AngelVelezSosa** [comment]
Is this a bug in Revit 2022 or Revit 2023?  We won't likely have more Revit 2021 updates.

**Comment by Moult** [comment]
This is a bug in Revit 2021. Are you sure this cannot be backported? Large projects move slow, and this type of bug also has the largest impact on large projects.

**Comment by AngelVelezSosa** [comment]
In general, no one has to downgrade - you can have a version of Revit 2023 around that is used only to export to IFC.  This of course is just a workaround since it is time consuming.  If this particular bug is particularly dangerous, we could patch the 2021 version on GitHub to contain this fix.

**Comment by erfajo** [comment]
I do understand your worries Angel, and I am sure that your resources are not unlimited.

However, as a larger driver of you being able to sell software in Autodesk, you also need to respect why we point towards your software. One major reason to choose Autodesk is the history of being able to maintain older projects, such a history is a key point to any owner. There is surely other software much newer and much smarter but without the history. If we will experience an increase in challenges, we have to consider why we point towards Autodesk Software.

You Angel are most certainly a major reason why we still are pointing towards Autodesk since you started this IFC Exporter application years ago. Thanks for all your hard work and efforts. And as you know am I coding nodes under my Orchid project for you IFC exporter, and I do maintain the nodes for the last four Revit/Dynamo versions, and that is for free for anyone who needs it :-)

A thing as layer assignment might very well be one of those which are going to be obsolete over time since we use CAD export/import in a very limited way, not to say nearly never. But it is still one of the requirements we have, being able to export to cad software.

**Comment by JOuellette-Autodesk** [comment]
https://jira.autodesk.com/browse/REVIT-186171

**Comment by JOuellette-Autodesk** [comment]
Fixed in Revit 2022 (IFC 2022.5).

**Comment by Moult** [comment]
The bug report specifies that this is an issue with 2021, so being fixed in 2022 doesn't help in this case because projects are still stuck on 2021, and it used to work on 2021. Why is this closed?

**Comment by AngelVelezSosa** [comment]
It is closed if it is fixed in a user-accessible version.  I absolutely understand the request to support 2021 and older versions, but we have to balance fixing bugs and backporting them.  Our balance is latest + previous release, plus the development release, which is 3 (and sometimes 4, when we are in the period between switching to a new development branch and putting the final touches on the previous branch) branches.   Most export issues do have a workaround of temporarily upgrading to a version where it is fixed.  I know that's annoying but it generally works.
