### ISSUE TITLE
not able to export

### ISSUE THREAD

**Issue by Teun1** [Autodesk/revit-ifc#379]
We are testing a VDI environment. And a Revit 2022 project could be exported on my local computer but not in the VDI environment.
They have the same exporter version v22.2.1.0 (not the latest I know - but they are the same) The VDI has the latest Revit2022 update and my local has not. So that could be the case.
But I am wondering if there are other critical aspects that would prevent an IFC export. Are there also hardware (memory etc.), or virus scanner options etc. that could possibly prevent an export. I have seen last year to many cases where an IF is not created and this worries me a little bit. 

Just 153 '_problem_' object in the VDI (without explanation) and a '_There has been an unrecoverable error during export. This may be because the file is too large to export. Try using filters and "Current View Only" mode, or look at the documentation for more suggestions. Export will now be aborted._' But nothing on my local, is really weird and not helping.

So before I update my local to a possible problem version. And upgrade both with the newest IFC exporter. 
I would like to know if there are more things to consider, if any. Thanks in advance.

**Comment by AngelVelezSosa** [comment]
The first thing to do is really to get both to the same level.  There were incompatibilities between Revit 2022.1 and the open source that were caused by the upgrade to ODA that really require the latest version of the exporter (or the OOTB version).  These should all be resolved now with Revit 2022.1.1 and v22.4 of the toolkit, but there are more mix-and-match issues this release because of the toolkit swap.

**Comment by Teun1** [comment]
Thanks for the reply. I will update these as soon as i can. And test it again.

**Comment by Teun1** [comment]
The updates did work. Thanks again.
