### ISSUE TITLE
 IfcSite elevation import problems

### ISSUE THREAD

**Issue by brunnefa** [Autodesk/revit-ifc#384]
As a Autodesk Partner Supporter, i currently get a lot of Problems with the IfcSite elevation in the newest Ifc2022/IFC2021 App. When importing an IFC with an elevation in IfcSite the model gets an additional elevation. However the IFC Building storeys are still on elevation 0. This was never a problem before and a total different behavior. The workaround of setting the Elevation in the Texteditor manually to 0 is not satisfying at all. Is there a way to handle this Problems better? 

![image](https://user-images.githubusercontent.com/95215630/143847343-aa137d51-a0c3-4430-b8d4-4b03bb5e9802.png)

**Comment by rolfarchi** [comment]
Hello everyone,

I sent the serious error "height problem" on 11/23/2021 with an Ifc test file directly to 'angel.velez@autodesk.com'.
Answer angel.velez: "We will look into this to see what’s going on."

The last working version is IFC.for.Revit.2022.2.1.0.

A manipulation of the data (elevation) in the Ifc file cannot be the solution.

The bug in the Ifc importer has to be fixed shortly.

Best regards

rolfarchi

**Comment by WawanSolihin** [comment]
Regarding this offset issue: The export data is actually correct. The RefElevation in IfcSite contains value that is expected according to the IFC specification, i.e. the actual elevation from the Mean Sea Level (or the geographic coordinate reference). The issue in this case is on import (LINK). The issue has been fixed in the main development branch, but not yet ported into the open source version.
Knowing that this causes a lot of issues to may of the users, I made a special fix that addresses the import (LINK) issue (a selected port from the main development version only the changes related to this issue). The unofficial build (unsigned) can be downloaded from [https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v22.4.1.0](https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v22.4.1.0). Please try it and see whether it solves the problem and let me know.

**Comment by brunnefa** [comment]
We tested it today and it works fine for us. Many Thanks.

**Comment by rolfarchi** [comment]
Hello,
tested, this problem solved.
Thank you very much.
