### ISSUE TITLE
Pset_ProvisionForVoid automatically assigned to wall profiles and slab edges

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#420]
When exporting wall profiles to IFC2x3, they are assigned the ProvisionForVoid property set. Is there any way of avoiding this?

![grafik](https://user-images.githubusercontent.com/3014437/154732102-8bda8019-0686-4a07-9e96-ab34ce675c4a.png)

EDIT: I see the same thing happening with slab edges as well.

![grafik](https://user-images.githubusercontent.com/3014437/154917806-5c511937-28ca-433f-8b75-b9b0b460716a.png)

**Comment by WawanSolihin** [comment]
This is a little "difficult" problem to solve. This is due to a different way of Revit manages parameters compared to IFC (no concept of propertyset). Therefore, Revit currently looks for the parameter names and match them to Pset(s) that defines those properties. In addition, this Pset is further narrowed by ObjectType="ProvisionForVoid", which is not supported by the exporter currently (only PredefinedType is supported).
One possible way to filter this out is to define the accepted list of entities and Psets inside IFCCertifiedEntitiesAndPSets.json (can be found inside the installation folder of the open source exporter, typically in "C:\ProgramData\Autodesk\ApplicationPlugins\IFC <Revit version>.bundle\Contents\<Revit version>". Currently inside the file define IFC4RV, and IFC4DTV MVDs. I have added IFC2x3 CV2.0 entities and Psets in there (Attached). You may want to test it by **_removing_** the Pset_ProvisionForVoid inside that file.

Hope that works for you.
[IFCCertifiedEntitiesAndPSets.zip](https://github.com/Autodesk/revit-ifc/files/8102575/IFCCertifiedEntitiesAndPSets.zip)


Wawan

**Comment by andydandy74** [comment]
@WawanSolihin Any way to fix this for IFC2x3?

**Comment by WawanSolihin** [comment]
Yes, please try it with the file I provided. You need to remove the entry under IFC2x3CV2 MVD, which currently includes Pset_ProvisionForVoid

**Comment by andydandy74** [comment]
Doesn't seem to work. I deleted the line in the JSON file, replaced the existing file in the addin folder and restarted Revit for good measure. The property set keeps being exported (22.4 exporter). So I guess that this means that any elements that get exported as ```IfcBuildingElementProxy``` and have one of those key parameters will have a ProvisionForVoid property set attached to them, right?

**Comment by WawanSolihin** [comment]
There are two issues: One is the MVD name is not correct (should be all capital), and also the code handles Pset_ProvisionForVoid differently (It is a special Pset). Therefore, I need to make modification to the code to be able to make it work.
I made a pre-release installer (not signed) here: https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v22.4.2.0
This installer contains the updated IFCCertifiedEntitiesAndPSets.json file that will be installed to the installation folder (open source). You still need to remove the Pset_ProvisionForVoid line inside the file. From my test it seems to work.

**Comment by eibre** [comment]
Nice! I did not know about this file. Is it possible to use this with the exporter included in Revit or do we need to use the open-source one?

**Comment by WawanSolihin** [comment]
Yes, it works also with the built-in one (as long as you see that the IFCCertifiedEntitiesAndPSets.json file exists in the Revit install folder. I do not remember exactly when this is implemented. It was for quite a while already.)

**Comment by andydandy74** [comment]
@WawanSolihin Just tested this with the installer you published. Works perfectly. Thanks! :-)
