### ISSUE TITLE
On export is there a way to set the `Precision` attribute higher for `IFCGEOMETRICREPRESENTATIONCONTEXT`?

### ISSUE THREAD

**Issue by theoryshaw** [Autodesk/revit-ifc#426]
On export is there a way to set the `Precision` attribute higher for `IFCGEOMETRICREPRESENTATIONCONTEXT`?

**Comment by AngelVelezSosa** [comment]
No, it is set based on the geometric tolerances of Revit itself.  Of course, that Precision value isn't very precise itself :)  What is it the precision of?  We use it to mean the value at which two vertices for a BRep (faceted or otherwise) would be coincident.  But meshes could have different (tighter) precisions for example.  I think it is generally a not very useful value.

**Comment by theoryshaw** [comment]
Gotcha. thx.  Is related to: https://github.com/IfcOpenShell/IfcOpenShell/issues/2053
