### ISSUE TITLE
Object with Revit warning is not exported

### ISSUE THREAD

**Issue by Teun1** [Autodesk/revit-ifc#432]
We had a generic model wich could not be exported to IFC.

While examining the issue it seems that the problem was that this object had a warning that Revit could, but the exporter could not handle. The object is roof based. But it was not cutting it's host. The host was in this case a sloped glazing roof.

We would expect the object to be exported just a it is visible in Revit.

I did a test with Revit 22.0.2.392. And the exporter 22.2.1.0. Not the newest. But the issue also occured in the newer version.
[220322_not_cutting_host.zip](https://github.com/Autodesk/revit-ifc/files/8323295/220322_not_cutting_host.zip)

![220322_revit_warning](https://user-images.githubusercontent.com/7262482/159458204-1750ee69-bf18-4156-a313-669cf60c1650.jpg)
![220322_viewer](https://user-images.githubusercontent.com/7262482/159458221-1cfe69a6-021e-470d-8699-a7fc253ffd1f.jpg)

**Comment by JOuellette-Autodesk** [comment]
https://jira.autodesk.com/browse/REVIT-189535

**Comment by AngelVelezSosa** [comment]
Hi @Teun1 , we are looking at this issue and are very confused :)  In particular, this seems like an odd case.  In particular, we have a case where you are trying to insert a skylight into a curtain roof.  Now, the standard workflow for adding a skylight to a curtain roof is to create a panel in the curtain roof and make it be the skylight.  In this case, though, you are trying to cut the curtain roof with the skylight, and that's never going to work (there's even a warning in Revit for that).  So IFC is confused because it doesn't expect an insert in a curtain roof (which doesn't work).  So the question is: is this an IFC error or is this a modelling error?

**Comment by parrela** [comment]
A separate roof opening cut would do it, and the skylight placed in it.

**Comment by Teun1** [comment]
Hi @AngelVelezSosa and @parrela, thanks for looking into this!
This is certainly an odd case ;-). The solution is to address the said warning. We were just curious why the exporter was having trouble with exporting a Family with a Revit error. But perhaps we should ignore this specific problem, and simply fix the Revit model. We can do that.

Just a thought on some improvement for the IFC exporter:
Would it be an idea to give the user some feedback / log after the export on what the exporter did or didn't do. In this case not exporting an object. The team was not aware, right away, that this Skylight was visible in Revit but not in the IFC. A report could help teams to step into problems more easy and fix it.
A quick solution, is to point users to specific geometric warnings (that are for grabs in the Revit model), and could affect the quality of the IFC. 
If your team is interested in some sort of report, we could start a new topic to get more feedback from other users on what seems useful and simple to report after an IFC export? Just to make the export more reliable. And fix occurrent problems faster by users. Simply because they know what could cause an IFC export problem. Or what has significant impact on the performance of the exporter, and should be simplified.
