### ISSUE TITLE
When will IFC4.3 be supported?

### ISSUE THREAD

**Issue by Martin15135215** [Autodesk/revit-ifc#519]
I like to know, when we can estimate, when will Revit be able to export to IFC4.3?

Something like a roadmap

**Comment by AngelVelezSosa** [comment]
That's not a simple question to answer.  There are a number of factors.
1. We are working on "basic" IFC4.3 export.  It is explicitly on our roadmap: https://trello.com/b/ldRXK9Gw/revit-public-roadmap which is a list of things we plan to do sooner than later.  I am not allowed to give you an exact timeframe.
2. IFC4.3, while it is "final", is not "final final" because it hasn't been ISO certified yet.  This will happen hopefully next year.
3. There are no official MVDs for IFC4.3.  So while we will be able to write out an IFC4.3 schema-complaint file, it will still be just "beta" or "experimental" support.

Hope that makes sense.
