### ISSUE TITLE
IFC2x3CV2.0: door issue & regression

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#55]
IFC2x3CV2.0
R2018 & R2019

Issue of the orientation of the parametric swing-symbol, and regression of the generation/translation to the correct OperationType, making use of the flip-functionality of doors.

Initial situation:
A door with a nested and shared doorpanel (with a plan swing line, without a value for Operation).
One door is modeled as single swing right (door_SSR)
One door is modeled as single swing left (door_SSL)

Action:
door_SSR is flipped over the Y-axe (resulting in 'door_SSR_Yflip')

Expectation:
door_SSR_Yflip should result in a door identically as door_SSL.

Result:
With 18.4 and 19.1: the operationtype is indeed correctly generated, but there seems to be an issue with the IFCAXIS2PLACEMENT3D, which causes a wrong orientation of the parametric symbol that is displayed in Solibri
Changing value 13
`"#295= IFCAXIS2PLACEMENT3D(#293,#19,#13)"`
to value 11
`"#295= IFCAXIS2PLACEMENT3D(#293,#19,#11)"`
seems to solve the direction, at least for Solibri.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/41319048/47414981-9a505680-d772-11e8-9f39-b2d24d6ec1c2.png">

But with the R19-current-version-in-the-DEV-branch, some disturbing regression is taking place.
The OperationType of the flipped one is not (anymore) correctly generated, and even the 'as is door_SSL' is now exporting as SSR.
And there is also the issue of the orientation of the parametric symbol.

![image](https://user-images.githubusercontent.com/41319048/47415018-b653f800-d772-11e8-9e4f-4a4aa2e860d4.png)

Attached, only the sample for R2018, since it's also upgradable to R2019.

[R2018_door.zip](https://github.com/Autodesk/revit-ifc/files/2509456/R2018_door.zip)

Regards,
Dirk

**Comment by WawanSolihin** [comment]
![Inkeddoor swing SSL_LI](https://user-images.githubusercontent.com/31854582/54845717-15636c00-4d15-11e9-922e-b365b5f14e57.jpg)
![Inkeddoor swing SSR_LI](https://user-images.githubusercontent.com/31854582/54845719-15fc0280-4d15-11e9-81ae-e376c7cefbbb.jpg)

The behavior may change in the latest 19.x codes to align the behavior according to the expected setup as required in IFC standard. The requirement is to place the reference point to be at the left/right corner and the +Y is where the swing direction points to. There is a work to improve the support of the operation type for IFC4RV certification and support more flexible swing curve size that now works not just 90 or 180 only.
The problem as reported above is related to the way the door is modelled where the reference point is at the center instead of the corner. To determine the correct operation type, the LEFT and RIGHT is evaluated based on whether the reference 0,0 is where the pivot point for the arc, if it is it will be determined as SWING LEFT, if not it is SWING RIGHT. Since in these cases all the doors have the reference point (0,0) in the middle it does not fulfill the criteria for SWING LEFT.

**Comment by dvrvb** [comment]
Hi Wawan,

Thanks for your extensive explanation. This is very helpful for modelling guides for doors: for good results the reference point should be in the corner instead of in the center.
I will alter this example and run a new test.

Best regards,
Dirk
