### ISSUE TITLE
R2018 exporter question

### ISSUE THREAD

**Issue by dvrvb** [Autodesk/revit-ifc#57]
Is my impression correct that there will be no more updates of the R18 exporter?

Regards,
Dirk

**Comment by AngelVelezSosa** [comment]
Unclear.  2018 updates become harder because 2018 is on SourceForge and 2019 is on Git.  That said, there may still be updates.

**Comment by dvrvb** [comment]
Is this the politically correct answer for saying: most probably not, unless higher forces are forcing to do so ... ?
Otherwise it's a bit a waste of time testing R2018 any further.

I'm wondering what is the meaning of the R2017 and R2018 branches (of Jon), since they are branches of the R2019 exporter?

**Comment by AngelVelezSosa** [comment]
Ha, no :)  Normally, we maintain the last 2 versions, which would be 2018 and 2019.  While 2018 is a little more painful, I still think we will improve.  Now, that said, generally we don't make 2018-only changes.  We make changes that affect 2019/internal development version and push those back to 2018 also.  So 2018 gets the benefit, but if there is a 2018 bug that's already fixed in 2019, then you'll have to upgrade (at least temporarily) to get the improvement.

**Comment by dvrvb** [comment]
OK :-) That's probably a comforting thought for the users actually running projects in R2018. As you probably noticed I mainly focus on R2019, because keeping track with one version is already challenging.
So, I'll close this issue/question.
Regards,
Dirk
