### ISSUE TITLE
export materials propertyset

### ISSUE THREAD

**Issue by SDA00** [Autodesk/revit-ifc#584]
Hello

The latest versions of IFC export on Revit 2022 and Revit 2023.1 bring a new feature "export materials propertyset"

I did not receive to understand what this feature brings in addition. Before, when exporting IFC, the different material layers were exported as IfcMaterial for walls, roofs, floors.

What does this new feature bring and how does it work? Is it necessary to add IFC properties in revit ?

 

Thanking you in advance

**Comment by AngelVelezSosa** [comment]
This allows you to export properties for the materials themselves. This isn't about material layers, it is about IfcProperties attached to IfcMaterials.

**Comment by SDA00** [comment]
Hello @AngelVelezSosa 

Thank you for your time. Can we for example export these properties?
![image](https://user-images.githubusercontent.com/92855523/215878903-aab69d58-424d-4e42-894f-03aef45d72b5.png)

**Comment by AngelVelezSosa** [comment]
I believe so - @t-vasyi , any issues there?

**Comment by SDA00** [comment]
Hello,

I work like many with ifc 2x3 and I saw that the ifcExtendedMaterialProperties was removed in ifc 4.3.x 
![image](https://user-images.githubusercontent.com/92855523/216392670-cc473292-edb1-4b57-9575-18d067066671.png)

The ifcExtendedMaterialProperties allows to get for example the Name or/and the description of a material 
it is defined as : Definition from IAI: A container class for user defined properties of associated material. This provides a mechanism to assign properties that have not been defined in IFC specification.
![image](https://user-images.githubusercontent.com/92855523/216392750-4da11d19-18c5-4b04-be35-58c359498ed2.png)


Today, using the ifc 2x3, is there a pset property that can be used to retrieve the value of the description field from the first screenshot.

Thank you in advance.

**Comment by t-vasyi** [comment]
Hi
I'm looking into it

**Comment by t-vasyi** [comment]
Hi,
The 'description' parameter from 'Identity' page is exported to 
IFC2x3: IfcExtendedMaterialProperties
IFC4: IfcMaterialProeprties
![image](https://user-images.githubusercontent.com/115650049/216731925-7e385fd2-4e6a-406d-b598-5663dd89bfa8.png)
![image](https://user-images.githubusercontent.com/115650049/216732079-a9ce4311-3470-48e3-b97f-646874d3ea68.png)

Here is a document that shows how 'IFC Material properties' export works
[IFC Material properties export.pdf](https://github.com/Autodesk/revit-ifc/files/10586974/IFC.Material.properties.export.pdf)

**Comment by SDA00** [comment]
Hi,

Thanks @t-vasyi  for the answer. It is very clear! 
Is it planned to make the material export work with ifc 2x3 Coordination View 2.0?

Thanks

**Comment by AngelVelezSosa** [comment]
We are trying to decide that now.  On the one hand, it is explicitly disallowed by the MVD.  On the other, it isn't on by default and could be considered an add-on.  Would be interested in hearing views.

**Comment by louistrue** [comment]
Would love that! 

This (and multilayer elements) is one of the major bottlenecks when working with IFC in Revit. There are so many use cases: circularity/sustainability, costing, model based production etc.

In combination with the item "real 3d wall/floor layers" from the Revit Roadmap, that would really be a game changer 👍

**Comment by YasmineArcadis** [comment]
Would love this possibility as well!

**Comment by JOuellette-Autodesk** [comment]
I appreciate everyone's desire for this additional functionality, but I need to remind everyone about the potential downsides.

When bSI creates "official" MVDs, like the IFC2x3 CV2.0 and IFC4 RV1.2, ALL vendors who certify on these exports must adhere strictly to the documented requirements. This ensures that the files are compatible and that expectations of their quality are well managed. If vendors start creating "unauthorized" variations of the MVD exports, then the buildingSMART community can point a finger at those vendors and claim they don't do IFC export properly.

I appreciate the custom export options people would like to utilize to enhance some data exchange workflows, but such options should only be applied to a custom IFC export configuration (MVD), not amended to the official bSI ones. So, I would suggest that any functional and UI enhancements only allow such option(s) to be applied to a "custom" or "user defined" IFC export configuration and the IFC file header reflecting such a type of file. Otherwise, you will sow more confusion among the greater buildingSMART community. 

If another vendor is enabling such violations of an MVD, please let me know. I would love the opportunity to remind them such work is NOT what was agreed to for certification.

**Comment by Teun1** [comment]
Thanks @JOuellette-Autodesk for the appriciated feedback on this subject.
I'am honestly interested in the reasons why material properties are not a part of the MVD. And also if those reasons are still valid at the moment. That might be the case.
Still I know we (users) have been asking Autodesk for a long time for something like this. And there are also some use cases mentioned above.
Is it enough to ask a question on the Building Smart Forum. Or are there other (better) ways to help get this on the agenda. 
I totaly agree that it is not usefull to develop something that does not work for others. Although sometimes it is usefull to simply start somewhere in order to help refocus on a subject.

**Comment by JOuellette-Autodesk** [comment]
Hi @Teun1,
Yeah, lots of decisions were made during their formulation (most involving the vendors first-hand), but they had distinct logic at the time. I think in this case, the biggest driver was trying to provide the most compatible, lowest complexity threshold of files to enable physical design coordination between disciplines of architecture, structure, and building services, across as many different applications and platforms as possible.

In the bSI Community, there has been a desire to address other workflows (e.g., visualization/rendering, structural analysis, energy analysis, etc.), but trying to "bend" the existing/previous MVDs to do that is not the best method. But, having the conversations and getting consensus to develop other MVDs for other workflows is the best path forward. 

Yes, I would encourage you to initiate and sustain more conversation on the bSI Forums https://forums.buildingsmart.org/

**Comment by SDA00** [comment]
Hello @JOuellette-Autodesk,

> any functional and UI enhancements only allow such option(s) to be applied to a "custom" or "user defined" IFC export configuration 

Maybe, at first, allowing to use the material properties in a custom/userdefined pset would be a big improvement and maybe not very elegant, but honestly the utility is more important than the elegance in this case.  👍

**Comment by Teun1** [comment]
I love this feature. And it works fine. At least for some testing purposes.
We can push all kinds of product information into Revit. Have the ability to add this information to objects and/or materials. Because some information is simply processed better at the meter level and others better at the object level. You can further place this information in the IFC for future reuse. As mentioned, it is not part of an official MVD. And I'm not aware of any tools that reuse this kind of information at this point.
The viewer in the photo is the FZK viewer. Other viewers such as Navisworks, Solibri, BIM Collab ZOOM etc. will obviously not show this kind of information as it is not part of an official MVD.
![1](https://user-images.githubusercontent.com/7262482/217227112-ff729b55-743e-48bc-b33c-12b35793df31.png)
![2](https://user-images.githubusercontent.com/7262482/217227113-b816caaf-6cd1-49af-aecc-16ac200053ad.png)
![3](https://user-images.githubusercontent.com/7262482/217227117-6db06d25-afd6-4ca4-9c95-009731de94bc.png)

**Comment by YasmineArcadis** [comment]
@Teun1 
Have you tested any other viewers: Blender/xbimxplorer/open ifc viewer/usbimviewer/bimvision? Do you have a test file which I can test these in for my reference?

**Comment by Teun1** [comment]
> 

[230207_RR_test_IfcMaterial_Properties.zip](https://github.com/Autodesk/revit-ifc/files/10675758/230207_RR_test_IfcMaterial_Properties.zip)
@YasmineArcadis Here you are. I would be pleased to hear your findings.
Blender might work. Xbimxplorer might also work. As I have seen test from Archicad with material properties in the past.

**Comment by Teun1** [comment]
Ok. I was definitly to fast with BIM Collab Zoom.
![4](https://user-images.githubusercontent.com/7262482/217269455-829a466a-ded0-4273-b0d1-c287e42a4920.png)

**Comment by AngelVelezSosa** [comment]
Question for the group: IFC4 does support the material properties.  Not an option?

**Comment by YasmineArcadis** [comment]
@Teun1 : only blenderbim and xbimxplorer work, though not as easily accessible as thought at first glance, the others don't support it as far as I can see.
![Blenderbim](https://user-images.githubusercontent.com/118900217/217290945-f46c3cc7-b42f-46f7-ae03-9050a10c6574.png)
![xbimxplorer](https://user-images.githubusercontent.com/118900217/217292041-6c9f5898-8713-43a5-8086-ccf25f032560.gif)

**Comment by AngelVelezSosa** [comment]
After consulting with various people, I am afraid that the only truly correct solution is to follow the rules of the IFC2x3 CV2.0 MVD and *not* include the properties that are disallowed.  Yes, it is easy enough to do so, and yes some viewers work (and some don't), but then we propagate a situation where we allow bad files and customer complaints of "but app X sees these properties..."  IFC4 does support, as will I hope all future versions of IFC, and I will talk to buildingSMART International to see if they would support a Material properties add-on to IFC2x3 to make it official.  But I don't know if they will want to do that, or instead give incentive to move to newer versions.

**Comment by Teun1** [comment]
> 
And the IFC2x3 version. 
I think if you wants this to work you will have to follow this 
https://github.com/Autodesk/revit-ifc/issues/584#issuecomment-1416540802. 

[230207_RR_test_Ifc2x3_IfcMaterial_Properties.zip](https://github.com/Autodesk/revit-ifc/files/10677047/230207_RR_test_Ifc2x3_IfcMaterial_Properties.zip)

**Comment by Teun1** [comment]
@YasmineArcadis thanks for the feedback.
@AngelVelezSosa Thanks in advance for checking on IFC2x3 with BuildingSmart.
And we'll see where this goes with future releases of IFC and MVDs.
My feeling is that there is a real use case with this one.
