### ISSUE TITLE
The new Shared Parameters Concept

### ISSUE THREAD

**Issue by PeterTranberg** [Autodesk/revit-ifc#599]
Is there documentation on how to use the new Shared Parameter Files?
We used to have only one Shared Parameter shared to individual categories, now the Shared Parameters are defined by Psets. Could anyone explain the concept or maybe add a wiki for best practice with Shared Parameters.

 It would also be great to have the rvt file for transferring shared parameters updated. 

Regards
Peter Tranberg

**Comment by PeterTranberg** [comment]
Found this https://sourceforge.net/p/ifcexporter/wiki/Supported%20property%20sets/
Is that guide still applicable?

**Comment by andydandy74** [comment]
Will the old Parameter names without psets still work?

**Comment by PeterTranberg** [comment]
> Found this https://sourceforge.net/p/ifcexporter/wiki/Supported%20property%20sets/ Is that guide still applicable?

@AngelVelezSosa Can you give any comment on this question? What is best practice for use of Shared Parameters in IFC?

**Comment by erfajo** [comment]
Wow... it looks like IfcExportAs, IfcExportType, IfcExportAs[Type], and IfcExportType[Type] disappear!?
However, looking in the code these user-defined overrides does still exist...
I also would like to know what is going on @AngelVelezSosa

**Comment by PeterTranberg** [comment]
> Wow... it looks like IfcExportAs, IfcExportType, IfcExportAs[Type], and IfcExportType[Type] disappear!? However, looking in the code these user-defined overrides does still exist... I also would like to know what is going on @AngelVelezSosa

@erfajo Notice that Revit now has new built-inn functionality for this part about Exporting IfcClasses and Predefined types, so there is no need for the parameters anymore.

**Comment by erfajo** [comment]
@PeterTranberg I didn't know... I will try to catch you to get some informations :-)

**Comment by AngelVelezSosa** [comment]
OK, a few comments:
1. Yes, the old shared parameters are gone and replaced by built-in ones.  On upgrade, we copy the values over to the new parameters but don't delete the old parameters in case you were using them in schedules or formulas or whatever.  The export code will ignore them otherwise it is a performance hit for obsolete functionality.
2. We now support all IFC common property sets, so that is obsolete.
3. Best practice: load in only the parameters you care about.  Use the full PsetName.PropertyName shared parameter to avoid setting parameters for property sets you don't want that happen to have the same name.  You can use Parameters Service to get the parameters you care about, or the shared parameters file and create a template.  We will look at the old PropertyName only parameters but you can get noise from those.
Did I miss anything? :)

**Comment by PeterTranberg** [comment]
Thanks @AngelVelezSosa, a few comments:
1 - What do you mean by "replaced by built-in once" does that mean that the code recognizes the new ones with full PsetName.PropertyName shared parameter and puts them i in the correct Pset?
2 - What is obsolete?
3 - Is it still mandatory to add IFC Shared Parameters to the IFC Parameters group in Revit?

**Comment by AngelVelezSosa** [comment]
Specifically the "IFC Export As" shared parameter that you had to type in an IFC class name or "Not Exported" if you didn't want the element to be exported has been replaced by two built-in parameters, Export to IFC and Export to IFC As, which has a tree for easier selection.  There is a corresponding type parameter and also ones for the predefined type.  All other ifc shared parameters must still be added via the shared parameters file or the Parameters Service on the cloud.

**Comment by gotoarchi** [comment]
You may want to [get familiar with the new Autodesk Parameter Service that hosts shared parameters in the cloud](https://goto.archi/blog/post/how-to-use-the-autodesk-parameter-service-in-revit) and that also has its own API. The shared parameter files will be replaced in the long term by this system.
