### ISSUE TITLE
IsExternal issues met generic models en de Common PropertySet

### ISSUE THREAD

**Issue by PVlug** [Autodesk/revit-ifc#672]
### Problem Description

Revit 2023.1.2
IfcExporter 23.3.1.0
IFC2x3
In some generic families, the IfcExternal (instance) parameter is not included in the common property set.
In the attached Revit file there are four generic families which are exported to different IfcClasses.

GM_trap -> IfcStairFlightType
GM_leakdorpel -> IfcCoveringType
GM_ventilationgrid -> IfcAirTerminalType
GM_beam -> IfcBeamType

The instance value IsExternal is different > true, false and not filled in for each placed instance.
The value is only placed in the Common property set with the beam, not with the other IfcClasses.

**[IsExternal Issues.zip](https://github.com/Autodesk/revit-ifc/files/12395463/IsExternal.Issues.zip)**

IsExternal (in dutch Uitwendig) is placed in the user defined property sets.

### Revit Version

2023.1.x

### IFC for Revit Addon Version

Other / None

### Windows Version

10 22H2

**Comment by PVlug** [comment]
@AngelVelezSosa 
Is this a bug or is something else going on?

**Comment by dvrvb** [comment]
Hallo/Hi Peter,

Correct me if I'm wrong, but I think a few things are happening at the same time:
(1) As far as I can remember it was till now normal behavior that a parameter was neglected on export if no value has been given to the parameter. So, in all the cases in the first row of your sample, where there is no type parameter, and where the instance parameter is 'untouched', the parameter "IsExternal" is skipped.
(2) Since you are exporting to IFC2x3, and for the IFC Classes in this example, only for the Beam the attribute IsExternal exists in IFC2x3. So that's the reason why only for that Class the attribute IsExternal is present in de Pset_BeamCommon.
In IFC4 IsExternal also exists for IfcCovering, and (as I tested) then it will also appear in the Pset_CoveringCommon.

So, in order to get it working on type level of the Generic Model, you could/should add the type parameter IfcExternal[Type], and tick or untick the option (but don't leave it untouched). In that case it will be recognized as a 'used' (type) attribute, and it will appear in the UserDefined Pset. 

Hope this helps a bit.

Groet/Regards,
Dirk

![image](https://github.com/Autodesk/revit-ifc/assets/41319048/5d4a73df-8127-498d-8096-beab6084835c)

**Comment by PVlug** [comment]
@dvrvb 
Hi Dirk,
Thanks for the reply.
I already suspected it had to do with the IfcClass and whether or not the IsExternal parameter is present or not, according to Building Smart.
The IsExternal parameter does indeed appear in the user Defined PropertySet. 😊
But the classification in Solibri only looks at the *Common property sets.

But it is clear why the IsExternal parameter cannot be found in all IfcClasses in the *common propertyset.
Kind regards, 
Met vriendelijk groet,
Peter

**Comment by dvrvb** [comment]
Hi Peter,
Exactly for that reason that you mentioned we (will) demand to write it to the UDPset. So the parameter IsExternal can be applied to each element, without considering if it it exists in the common Pset or not.
Regards,
Dirk

**Comment by AngelVelezSosa** [comment]
Thanks for the help here @dvrvb while I was out!  Sounds like this is working as designed (where the design could be haggled with buildingSMART...)
