### ISSUE TITLE
INQ: Exported etities share the same property value, even though they are not the same type

### ISSUE THREAD

**Issue by semhustej** [Autodesk/revit-ifc#698]
### Inquiry description

When exporting IFC from Revit with several types of Doors as an example, the value of IsExternal property is exported pointing to one line (#164 in attached example). When the value of the property IsExternal of one type is changed in IFC editing tool, the value changes in all types at once - because it points to the same line. I think it should be possible to edit values of properties for each type independently.

It would be understandable for Reference View MVD, but I tested with Design Transfer View MVD, with the same result. I am not too familiar with IFC schema, but I thought Design Transfer View MVD is meant to be editable. 

See  .rvt source file and exported IFC file:
IFC
https://1drv.ms/u/s!Arsa_KlV4VjQlDSwgA7K3ZyVnuKK?e=v1h3qf
RVT
https://1drv.ms/u/s!Arsa_KlV4VjQlDVKodvj_COeyLQ2?e=n5O2k5

![door-types](https://github.com/Autodesk/revit-ifc/assets/149316569/39e72823-102f-428c-9b6e-cba6393504a5)

### Revit Version

2024.0.x

### IFC for Revit Addon Version

24.x.x

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
This is by design.  The alternative is to have thousands or tens of thousands of propertysinglevalues.  Note that properties do not have guids.

If you are manually changing the file and want to change one occurrence, instead change the step id in the ifcpropertyset.  But you probably shouldn't be manually changing it.
