### ISSUE TITLE
PitchAngle in Pset_SlabCommon

### ISSUE THREAD

**Issue by HenkMolhoek** [Autodesk/revit-ifc#73]
Hi All,

I encountered an error with exporting sloped floors from revit to ifc using the IFC For revit exporter. I also found out what the error is. The slope in revit is defined as slope, not in radians. (for an explanation, see jeremy's blog post about it http://thebuildingcoder.typepad.com/blog/2010/08/slope-is-slope-not-radians.html ) However, the IFC exporter converts the internal slope value as if it is a slope defined in radians.

Solution: When converting slope from internal revit units to degrees, apply the inverse tangens to the internal revit value. This will result in the correct degree value. Can this be fixed?

Thanks!
![revit_slope](https://user-images.githubusercontent.com/45469583/49636079-dcbbb300-fa01-11e8-9a9f-0218fe1da44d.png)
![ifc_slope](https://user-images.githubusercontent.com/45469583/49636082-df1e0d00-fa01-11e8-9fda-ae82598c0387.png)

**Comment by HenkMolhoek** [comment]
It is still open.
If I have a floor with a slope of 30 degrees. Then this is ifc is 57 degrees. This occurs in ifc2x3 and ifc4
[Sample Files.zip](https://github.com/Autodesk/revit-ifc/files/4993512/Sample.Files.zip)

**Comment by AngelVelezSosa** [comment]
Thanks for the simple sample file - it was easy to reproduce the issue.  Will try to fix in an upcoming update.

**Comment by WawanSolihin** [comment]
This issue has been fixed in the latest version of exporter. The PitchAngle will be in degree as agreed within IFC implementation. The IfcProject has the appropriate IfcConversionBasedUnit that specifies the conversion from Radian value (SI standard) to the Degree angle.
[test ifc exporter-new.zip](https://github.com/Autodesk/revit-ifc/files/6022699/test.ifc.exporter-new.zip)
Attached is the example of the export for Sample Files.zip. The slab has PitchAngle 45 degree (which is the slope).
