### ISSUE TITLE
PR: Lots of custom propertys (custom Pset) not visible in IFC

### ISSUE THREAD

**Issue by WillemdBr** [Autodesk/revit-ifc#758]
### Problem Description

with the latest exporter of 2022 (22.7) lots of property's exported with a custom propertyset, are not exported within that custom property set. 

I think this is a big bug because the same custom Pset file always worked for us, but not with this latest version. 

For example I miss these propertys (and many others..):

- 03 - Omschrijving	Text	Description
- 01 - NL-SfB code	Text	Assembly Code
- 04 - Fabrikant	Text	Manufacturer
- 08 - Opmerkingen	Text	Comments
- lengte	Length	lengte
- is uitwendig	Boolean	IsExternal

Files are attached:
[Custom Pset test.zip](https://github.com/Autodesk/revit-ifc/files/14905738/Custom.Pset.test.zip)

### Revit Version

2022.1.x

### IFC for Revit Addon Version

22.6.2

### Windows Version

11 22H2

**Comment by WillemdBr** [comment]
@AngelVelezSosa @WawanSolihin Are you familiair with this issue?

**Comment by o-babii** [comment]
Hello @WillemdBr, 
In the 22.7 update, we introduced some changes in the handling of custom property sets. 
In this case, the properties are lost because it is type properties and requires an explicit mention in the PSet file (such as IfcElementType) to be exported. 
I modified your custom pset file and now the lost properties are exported. 

Here is an example from pset file:
_###	Class:	IfcElement	
PropertySet:	UMCG_Eigenschappen	I	IfcElement **IfcElementType IfcDoorStyle IfcWindowStyle**_

I added IfcElementType for most of the type properties, but in IFC2x3 it doesn't work for windows and doors, because they have their own type entities that do not inherit from IfcElementType, so I specified IfcDoorStyle and IfcWindowStyle separately.

Also, 
_###	Class:	IfcPile	
PropertySet:	UMCG_Eigenschappen	I	IfcPile **IfcPileType**_

_###	Class:	IfcSpatialStructureElement	
PropertySet:	UMCG_Ruimteclassificatie	I	IfcSpace **IfcSpaceType**_

As a result, using the new pset file UPD_Custom Pset test.txt 
[UPD_Custom Pset test.zip](https://github.com/Autodesk/revit-ifc/files/14917720/UPD_Custom.Pset.test.zip)

![image](https://github.com/Autodesk/revit-ifc/assets/25076346/7e884ea4-121b-46ad-8590-30642bba0630)

@WillemdBr, please, try to use the updated PSet file (the upset file and my export result are attached) and verify if this is works for you.

Regards,
Oleksandr

**Comment by WillemdBr** [comment]
Thanks for your reply @o-babii , We'll adjust our Custom Pset files
