### ISSUE TITLE
PitchAngle in Pset_SlabCommon always reports 0° for floor slabs

### ISSUE THREAD

**Issue by andydandy74** [Autodesk/revit-ifc#8]
While ```IfcSlab```s in ```IfcRoof```s correctly report their ```PitchAngle``` in ```Pset_SlabCommon```, ```IfcSlab```s generated from Revit floor slabs do not - they always report 0°, regardless of the actual slope.

Tested in 18.4

**Expected behaviour:** 
Either report the actual slope using the method already available for roofs or only export this property for horizontal slabs.

**Steps to reproduce**
* Open and export the file below
https://github.com/andydandy74/MyIssues/raw/master/RevitIFC8/SlabCommon_PitchAngle.rvt
* Examine the ```PitchAngle``` values in ```Pset_SlabCommon``` of the respective floor slabs
* Notice they all are 0°

**Comment by WawanSolihin** [comment]
What is expected in this case? There are 2 floors that have Slope angle 5 degree, and the other 2 do not have.
Is it expected that only the 2 Floors with Slope angle 5 degree will have the Pitch Angle in Pset_SlabCommon, whereas the other 2 will have value 0 or no PitchAngle property?
Currently with some works on IFC4 Certification, the result above is obtained.

**Comment by andydandy74** [comment]
**All** four floors are sloped, albeit each by a different method available in Revit. 
Any sloped **roofs** created by the exact same methods correctly report their PitchAngle when exporting to IFC2x3.
I would expect the same to work for floor slabs (i.e. recycle the code used for roofs). At the very least, I would expect the exporter to not export a property with a wrong value (i.e. 0° when the floor slab clearly isn't horizontal).

**Comment by WawanSolihin** [comment]
The issue is a little complicated because currently the pitch angle or slope is calculated only on an extrusion body. In this case, the 2 middle slabs are not identified as extrusions (probably because they are not extruded perpendicularly, or simply the ExtrusionAnalyzer is unable to identify the appropriate extrusion) and therefore it does not compute the slope.
In commit 1e10b35, and additional logic for the slope calculation is added by looking as the slope of the top facing largest face to compute the slope/pitch angle. Tested against the attached test case, it shows different pitch angles for each of the slabs that looks correct.

**Comment by dvrvb** [comment]
Just an intermediate test for R2019:
indeed it's fixed for IFC4RV1.2, but not yet for IFC2x3CV2.0
![image](https://user-images.githubusercontent.com/41319048/46569849-6647f980-c95b-11e8-97a8-fb1412079011.png)

**Comment by WawanSolihin** [comment]
This issue has been fixed as tested in the latest releases: 21.2.0.0, 20.3.1.0, and 19.5.0.0 (coming soon). The example exports are atacched (for IFC4 RV 1.2, and for IFC2x3).
[SlabCommon_PitchAngle.zip](https://github.com/Autodesk/revit-ifc/files/5933917/SlabCommon_PitchAngle.zip)
